<a href="https://colab.research.google.com/github/boongtol1/2025-1-myclass-BDA/blob/main/inclass/03w_A_mon_0324_dataframe_application.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 단원 7 데이터프레임 정보와 검색 활용


## 데이터프레임 정보와 수정

In [2]:
!git clone https://github.com/ai7dnn/data

Cloning into 'data'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 20 (delta 3), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (20/20), 2.12 MiB | 5.42 MiB/s, done.
Resolving deltas: 100% (3/3), done.

In [6]:
import pandas as pd

df=pd.read_csv('data/2016년졸음운전.csv',encoding='euc-kr')
df

          연월  사고(건)  사망(명)  부상(명)
0    2016년1월    192      5    387
1    2016년2월    174      6    328
2    2016년3월    217      7    435
3    2016년4월    216      7    419
4    2016년5월    239     13    522
5    2016년6월    200     12    362
6    2016년7월    227      9    460
7    2016년8월    230      7    490
8    2016년9월    187     13    347
9   2016년10월    183     10    367
10  2016년11월    200      5    418
11  2016년12월    168      4    364

In [14]:
import pandas as pd

df=pd.read_csv('data/2016년졸음운전.csv',encoding='euc-kr',index_col=0)
df

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [8]:
df.dtypes

연월       object
사고(건)     int64
사망(명)     int64
부상(명)     int64
dtype: object

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   연월      12 non-null     object
 1   사고(건)   12 non-null     int64
 2   사망(명)   12 non-null     int64
 3   부상(명)   12 non-null     int64
dtypes: int64(3), object(1)
memory usage: 516.0+ bytes

In [12]:
df.head()

        연월  사고(건)  사망(명)  부상(명)
0  2016년1월    192      5    387
1  2016년2월    174      6    328
2  2016년3월    217      7    435
3  2016년4월    216      7    419
4  2016년5월    239     13    522

In [15]:
df.tail()

          사고(건)  사망(명)  부상(명)
연월
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [17]:
df.describe()

            사고(건)      사망(명)       부상(명)
count   12.000000  12.000000   12.000000
mean   202.750000   8.166667  408.250000
std     23.014324   3.186144   60.051682
min    168.000000   4.000000  328.000000
25%    186.000000   5.750000  363.500000
50%    200.000000   7.000000  402.500000
75%    219.500000  10.500000  441.250000
max    239.000000  13.000000  522.000000

In [18]:
df.sum()

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [19]:
df.sum(axis=0)

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [20]:
df.sum(axis=1)

연월
2016년1월     584
2016년2월     508
2016년3월     659
2016년4월     642
2016년5월     774
2016년6월     574
2016년7월     696
2016년8월     727
2016년9월     547
2016년10월    560
2016년11월    623
2016년12월    536
dtype: int64

In [21]:
df.cumsum(axis=0)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     366     11    715
2016년3월     583     18   1150
2016년4월     799     25   1569
2016년5월    1038     38   2091
2016년6월    1238     50   2453
2016년7월    1465     59   2913
2016년8월    1695     66   3403
2016년9월    1882     79   3750
2016년10월   2065     89   4117
2016년11월   2265     94   4535
2016년12월   2433     98   4899

In [22]:
df.cumsum(axis=1)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192    197    584
2016년2월     174    180    508
2016년3월     217    224    659
2016년4월     216    223    642
2016년5월     239    252    774
2016년6월     200    212    574
2016년7월     227    236    696
2016년8월     230    237    727
2016년9월     187    200    547
2016년10월    183    193    560
2016년11월    200    205    623
2016년12월    168    172    536

In [24]:
df.mean(axis=0)

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [25]:
df.mean(axis=1)

연월
2016년1월     194.666667
2016년2월     169.333333
2016년3월     219.666667
2016년4월     214.000000
2016년5월     258.000000
2016년6월     191.333333
2016년7월     232.000000
2016년8월     242.333333
2016년9월     182.333333
2016년10월    186.666667
2016년11월    207.666667
2016년12월    178.666667
dtype: float64

In [26]:
df.mean(axis=None)

np.float64(206.38888888888889)

In [28]:
df.max()

사고(건)    239
사망(명)     13
부상(명)    522
dtype: int64

In [29]:
df.max(axis=1)

연월
2016년1월     387
2016년2월     328
2016년3월     435
2016년4월     419
2016년5월     522
2016년6월     362
2016년7월     460
2016년8월     490
2016년9월     347
2016년10월    367
2016년11월    418
2016년12월    364
dtype: int64

In [30]:
df.max(axis=None)

522

In [31]:
df.min()

사고(건)    168
사망(명)      4
부상(명)    328
dtype: int64

In [33]:
df.min(axis=None)

4

In [34]:
df

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

# 데이터프레임 수정

In [35]:
df[['사망(명)','부상(명)']].sum(axis=1)

연월
2016년1월     392
2016년2월     334
2016년3월     442
2016년4월     426
2016년5월     535
2016년6월     374
2016년7월     469
2016년8월     497
2016년9월     360
2016년10월    377
2016년11월    423
2016년12월    368
dtype: int64

In [36]:
df.iloc[:,1:].sum(axis=1)

연월
2016년1월     392
2016년2월     334
2016년3월     442
2016년4월     426
2016년5월     535
2016년6월     374
2016년7월     469
2016년8월     497
2016년9월     360
2016년10월    377
2016년11월    423
2016년12월    368
dtype: int64

In [38]:
df2=df.copy()
df2['재해재수']=df[['사망(명)','부상(명)']].sum(axis=1)
df2

          사고(건)  사망(명)  부상(명)  재해재수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368

In [40]:
df2.loc['총계']=df2.sum()
df2

          사고(건)  사망(명)  부상(명)  재해재수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368
총계         4866    196   9798  9994

In [41]:
df2>10

          사고(건)  사망(명)  부상(명)  재해재수
연월
2016년1월    True  False   True  True
2016년2월    True  False   True  True
2016년3월    True  False   True  True
2016년4월    True  False   True  True
2016년5월    True   True   True  True
2016년6월    True   True   True  True
2016년7월    True  False   True  True
2016년8월    True  False   True  True
2016년9월    True   True   True  True
2016년10월   True  False   True  True
2016년11월   True  False   True  True
2016년12월   True  False   True  True
총계         True   True   True  True

In [42]:
df[df2>10]

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192    NaN    387
2016년2월     174    NaN    328
2016년3월     217    NaN    435
2016년4월     216    NaN    419
2016년5월     239   13.0    522
2016년6월     200   12.0    362
2016년7월     227    NaN    460
2016년8월     230    NaN    490
2016년9월     187   13.0    347
2016년10월    183    NaN    367
2016년11월    200    NaN    418
2016년12월    168    NaN    364

In [47]:
[[True,False]*6+[True]]

[[True,
  False,
  True,
  False,
  True,
  False,
  True,
  False,
  True,
  False,
  True,
  False,
  True]]

In [48]:
df2[[True,False]*6+[True]]

          사고(건)  사망(명)  부상(명)  재해재수
연월
2016년1월     192      5    387   392
2016년3월     217      7    435   442
2016년5월     239     13    522   535
2016년7월     227      9    460   469
2016년9월     187     13    347   360
2016년11월    200      5    418   423
총계         4866    196   9798  9994

In [51]:
df2['재해재수']>400

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월      True
2016년6월     False
2016년7월      True
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월     True
2016년12월    False
총계           True
Name: 재해재수, dtype: bool

In [52]:
df2[df2['재해재수']>400]

          사고(건)  사망(명)  부상(명)  재해재수
연월
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년11월    200      5    418   423
총계         4866    196   9798  9994

In [ ]:
df2['사망(명)'].isin(7,4)

In [58]:
df2[df2['사망(명)'].isin([7, 4]) | df2['부상(명)']>350]

Empty DataFrame
Columns: [사고(건), 사망(명), 부상(명), 재해재수]
Index: []

In [59]:
df[df.index.str.contains('3')]

         사고(건)  사망(명)  부상(명)
연월
2016년3월    217      7    435